### ISSUE TITLE
Got a error upon load up. Seems to be from the latest update reworking chiseled bookshelves. (1.20.1)

### ISSUE THREAD

**Issue by Israphelite** [Jusey1/Woodster#5]
[latest.log](https://github.com/Jusey1/Woodster/files/14224577/latest.log)
[crash-2024-02-09_12.20.18-fml.txt](https://github.com/Jusey1/Woodster/files/14224579/crash-2024-02-09_12.20.18-fml.txt)

**Comment by Jusey1** [comment]
Every Compact needs to be updated. I already fixed this issue on their end, they just need to release the update.
